### PR TITLE
Api tests redux

### PR DESCRIPTION
**Pull request by bwalsh**
This PR contains one new feature:
  * swagger driven API server
     * compliant with most recent GA4GH Beacon
     * facade for elastic search
     * integration tests

( this is a replacement for #96 from March 2)

### CODE REVIEW

**Comment by bwalsh** [comment]
@ahwagner @mayfielg : any comments?  I'd like to merge

**Comment by ahwagner** [comment]
Thanks @bwalsh. Will review this afternoon.

**Review by ahwagner — COMMENTED** [review]
These tests look fine, as do the changes to the GA4GH beacon response. @bwalsh, would you be able to provide some basic instructions for spinning up a test instance of the API? If they already exist, please point me at them and I'll test it out--otherwise we should incorporate those directions somewhere in the repo.

**Comment by bwalsh** [comment]
@ahwagner  I've included instructions to launch API and nginx in the readme

**Pull request merged**
