### PR TITLE
Issue 129

### PR DESCRIPTION
**Pull request by ahwagner**
in progress revisions for #129. Placing here to track progress, not ready for review.

### CODE REVIEW

**Comment by ahwagner** [comment]
@bwalsh this is ready for a preliminary review. Not testing the Jax entry yet, as Jax endpoint used by our harvester is currently offline.

I've contacted Sue Mockus, who is going to work with Dan at Jax to get it back online for us.

Worst case scenario, we could always custom-process the existing JAX-CKB set through the normalizer, though ideally we can simply re-harvest.

**Comment by bwalsh** [comment]
Thanks @ahwagner - to reproduce the new dataset, should I re-harvest all the sources?

**Comment by ahwagner** [comment]
@bwalsh sounds great, thanks for offering.

**Review by ahwagner — COMMENTED** [review]
This is working mostly as intended, but an additional change is needed before merge: https://github.com/ohsu-comp-bio/g2p-aggregator/issues/129#issuecomment-466389690

**Comment by ahwagner** [comment]
@bwalsh ready for review

**Comment by ahwagner** [comment]
@bwalsh any objections to merge? Want to make this v0.12 official in line with submitted manuscript.

**Comment by bwalsh** [comment]
> @bwalsh any objections to merge? Want to make this v0.12 official in line with submitted manuscript.

@ahwagner None.  Go ahead and merge

**Pull request merged**
