### PR TITLE
GENIE analysis additions & CGI/OncoKB validated oncogenic mutations normalizations

### PR DESCRIPTION
**Pull request by grmayfie**
Contains: 
* additions to GENIE analysis that replicate CGI paper and OncoKB paper analyses
* new normalizer at harvest level (after harvesters run) which creates additional new associations based on validated oncogenic mutations from CGI and OncoKB
* phenotype grabbing in the g2p client used by the GENIE notebook

In order to run the new normalization, you will need to download http://oncokb.org/api/v1/utils/allAnnotatedVariants.txt and https://www.cancergenomeinterpreter.org/data/catalog_of_validated_oncogenic_mutations_latest.zip and drop it into `g2p-aggregator/data/`.

@bwalsh @jgoecks

### CODE REVIEW

**Comment by bwalsh** [comment]
@mayfielg thanks. the code looks great.  trying to run GENIE notebook now.
where can I find the following files?  thanks.

image

**Comment by bwalsh** [comment]
@mayfielg Can we document the source and naming of these files?
```
        CGI_TABLE = CGI_Oncogenic('../data/cgi_oncogenic_mutations.tsv')
```

```
         ONCOKB_TABLE = ONCOKB_Oncogenic('../data/oncokb_all_mutations.tsv')
```

**Comment by bwalsh** [comment]
@mayfielg Based on your description of oncogenic mutations, I'm not sure I see them in g2p?

image



Based on the oncokb screens, I would have expected the query `+BRCA2 +Rucaparib +R2659T` to produce a hit.
At the same time, `+BRCA2 +R2659T` produces 3 identical hits, associated with `cancer`

image

**Comment by bwalsh** [comment]
The oncogenic features seem to be bypassing feature enrichment...

#### enriched feature
image

#### same feature in an oncogenic record
image

**Comment by bwalsh** [comment]
@mayfield I'm curious about the intersection of the oncokb section of this PR and commit  `pull biological variants` #46  from 4 months ago.

A small change to that commit would be:

```
diff --git a/harvester/oncokb.py b/harvester/oncokb.py
index aa0b718..c811e05 100644
--- a/harvester/oncokb.py
+++ b/harvester/oncokb.py
@@ -56,21 +56,9 @@ def convert(gene_data):
     global LOOKUP_TABLE
     gene = gene_data['gene']
     oncokb = {'clinical': [], 'biological': []}
-    if 'oncokb' in gene_data:
-        oncokb = gene_data['oncokb']
-    for clinical in oncokb['clinical']:
-        variant = clinical['variant']
-        alteration = variant['alteration']
-        gene_data = variant['gene']
-
-        feature = {}
-        feature['geneSymbol'] = gene
-        feature['name'] = variant['name']
-        feature['description'] = variant['name']
-        feature['entrez_id'] = gene_data['entrezGeneId']
-        feature['biomarker_type'] = mut.norm_biomarker(
-            variant['consequence']['term'])

+    def _enrich_feature(gene, feature):
+        global LOOKUP_TABLE
         # Look up variant and add position information.
         if not LOOKUP_TABLE:
             LOOKUP_TABLE = cosmic_lookup_table.CosmicLookup(
@@ -88,6 +76,43 @@ def convert(gene_data):
             feature['referenceName'] = str(match['build'])
         else:
             feature = enrich(feature)
+        return feature
+
+    if 'oncokb' in gene_data:
+        oncokb = gene_data['oncokb']
+    # this section yields a feature association for the predictive evidence
+    for clinical in oncokb['clinical']:
+        variant = clinical['variant']
+        alteration = variant['alteration']
+        gene_data = variant['gene']
+
+        # if feature is 'Oncogenic Mutations' then merge in biological
+        features = []
+        if variant['name'] == 'Oncogenic Mutations':
+            for biological in oncokb['biological']:
+                if biological['oncogenic'] in ['Likely Oncogenic', 'Oncogenic']:
+                    variant = biological['variant']
+                    gene_data = variant['gene']
+                    alteration = variant['alteration']
+                    feature = {}
+                    feature['geneSymbol'] = gene
+                    feature['description'] = variant['name']
+                    feature['name'] = variant['name']
+                    feature['entrez_id'] = gene_data['entrezGeneId']
+                    feature['biomarker_type'] = mut.norm_biomarker(
+                        variant['consequence']['term'])
+                    feature = _enrich_feature(gene, feature)
+                    features.append(feature)
+        else:
+            feature = {}
+            feature['geneSymbol'] = gene
+            feature['name'] = variant['name']
+            feature['description'] = variant['name']
+            feature['entrez_id'] = gene_data['entrezGeneId']
+            feature['biomarker_type'] = mut.norm_biomarker(
+                variant['consequence']['term'])
+            feature = _enrich_feature(gene, feature)
+            features.append(feature)

         association = {}
         association['description'] = clinical['level_label']
@@ -128,15 +153,17 @@ def convert(gene_data):
                 break

         association['drug_labels'] = ','.join([drug for drug in clinical['drug']])   # NOQA
-        feature_names = feature["geneSymbol"] + ' ' + feature["name"]
+        feature_names = ', '.join(['{}:{}'.format(
+                                f["geneSymbol"], f["name"]) for f in features])
         feature_association = {'genes': [gene],
-                               'features': [feature],
+                               'features': features,
                                'feature_names': feature_names,
                                'association': association,
                                'source': 'oncokb',
                                'oncokb': {'clinical': clinical}}
         yield feature_association

+    # this section yields a feature association for the oncogenic evidence
     for biological in oncokb['biological']:
         variant = biological['variant']
         gene_data = variant['gene']
```

This associates all oncogenic variants for the gene tagged  ['Likely Oncogenic', 'Oncogenic'] with the predictive evidence.  All features are then processed by the downstream normalization

image


*Suggest*: deprecating the oncokb sections of oncogenic_normalizer

**Comment by bwalsh** [comment]
Are these the source of the notebook files?
http://www.cbioportal.org/study?id=msk_impact_2017#summary

**Comment by bwalsh** [comment]
GENIE_VARIANTS

image

suggest
`            p = str(row['phenotype'].encode('utf-8').lower())`

**Comment by grmayfie** [comment]
Hey Brian, 

In reference to the first question: honestly I've now forgotten where I got those files., for certain. The link you've provided looks right to me, but I need to check in the OncoKB paper. 

In reference to `../data/cgi_oncogenic_mutations.tsv` and `../data/oncokb_all_mutations.tsv`that's what I named the files I mentioned you'll need at the top of this PR. 

As for code questions, I don't know what you're referring to as feature enrichment. What are you not seeing in g2p? Also, are you not seeing it before or after harvesting with this code?

**Comment by bwalsh** [comment]
@mayfielg merged in code, will create issue to track notebook files

**Pull request merged**
