### PR TITLE
Feature enricher

### PR DESCRIPTION
**Pull request by bwalsh**
This PR addresses #88 
* leverages `mygene.info` and `myvariant.info`  to lookup feature and gene locations
*  improves 68.4% of associations with variant start/end coords to **92%**
* extracts placed on s3://g2p-0.9

@ahwagner : can you re-run with your notebook?  My results:

* image

Known issues:
* attached file details misses
  * [no_coord_featured.tsv.txt](https://github.com/ohsu-comp-bio/g2p-aggregator/files/1750953/no_coord_featured.tsv.txt)

### CODE REVIEW

**Comment by bwalsh** [comment]
update: improved edge cases

 
image

**Comment by grmayfie** [comment]
Looks like this also addresses [#89](https://github.com/ohsu-comp-bio/g2p-aggregator/issues/89) and [#85](https://github.com/ohsu-comp-bio/g2p-aggregator/issues/85), yeah?

Deals with #88 by getting missing info from mygene.info rather than mutalyzer or ensembl like Alex suggested. Is there any data we miss that we might want using mygene.info instead. It does seem to be a simpler API method.

**Comment by bwalsh** [comment]
This PR needs to address https://github.com/ohsu-comp-bio/g2p-aggregator/issues/92 as well

**Comment by grmayfie** [comment]
The cosmic code was not taking into account transcripts in the cosmic TSV. So for cases like 'FGFR3 Y375C', which exists in cosmic as 'FGFR3_ENST00000340107 p.Y375C', the matches weren't getting picked up. This should be resolved now.

**Comment by bwalsh** [comment]
I’ve exported new files to https://s3.console.aws.amazon.com/s3/buckets/g2p-0.9
 
* cgi “collapsed” - now 1073 associations was ~1400
* georgia’s cosmic fix

**Pull request merged**
