### PR TITLE
Genie analysis Test PR 

### PR DESCRIPTION
**Pull request by bwalsh**
Test PR

### CODE REVIEW

**Comment by ahwagner** [comment]
Hey @bwalsh and @jgoecks, is this ready for review?

**Comment by bwalsh** [comment]
@ahwagner  Yes, I've merged this and tested it locally.   I will push the merged version later today

**Comment by grmayfie** [comment]
Why is this in v0.4 rather than v0.5?

**Comment by bwalsh** [comment]
@mayfielg - I haven't pushed this yet.  I can push it to 0.5   ( once I get past an issue I'm having with molecularmatch )

**Comment by bwalsh** [comment]
merged to v0.5

**Pull request closed without merging**
