### PR TITLE
Oncokb api

### PR DESCRIPTION
**Pull request by grmayfie**
Take 2

### CODE REVIEW

**Comment by grmayfie** [comment]
Reverted @bwalsh

**Comment by grmayfie** [comment]
@bwalsh I'm unable to replicate the problem you mentioned of the new oncokb biological only showing 'likely oncogenic' results. This is what I see. 

screen shot 2017-09-18 at 4 45 43 pm

What visualization are you using to get the previous count?

**Comment by grmayfie** [comment]
@bwalsh "found the problem w/ oncogenic … It was w/ my change for civic.  New values (include my change for civic oncogenic)"

Are the CIVIC changes you made incorporated into this PR? Can we close?

**Comment by bwalsh** [comment]
merged to 0.5

**Pull request closed without merging**
